<a href="https://colab.research.google.com/github/calebebrim/algoritmo-genetico/blob/master/Notebooks/Aplica%C3%A7%C3%A3o_Algoritmos_Gen%C3%A9ticos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Instalando Ambiente
criado a aplicação



In [83]:
!git clone https://github.com/calebebrim/geneticalgorithm.git

Cloning into 'geneticalgorithm'...
remote: Enumerating objects: 138, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 138 (delta 4), reused 15 (delta 3), pack-reused 116
Receiving objects: 100% (138/138), 108.48 KiB | 4.93 MiB/s, done.
Resolving deltas: 100% (38/38), done.


Alterando a pasta raiz


In [84]:
%cd /content/geneticalgorithm
!ls

/content/geneticalgorithm
dist		  geneticalgorithm.py  LICENCE	 Notebooks  setup.py
geneticalgorithm  __init__.py	       Makefile  README.md  src


# Executando os exemplos

Minimization: 

$e =$ number count
$e =$ number count

$F(e) = min(\sum_{i=0}^e(n_i))$

having

$(n_i 𝛜 𝓝 | n<=10)$  


In [85]:
!make minimization

python -m src.examples.sum_minimization
nbits: 4
Generating Population With: 
	- Gene Size: 8
	- Population Size: 10
	- Population Type: <class 'bool'>
	- Generations: 1000
	- Generations for each ephoch: 100
	- Selection Count: 10
            
================(Epoch: 1 Generation: 100)=======================
{'max': 22, 'min': 4, 'avg': 13.6}
Best:  0
================(Epoch: 1 Generation: 100)=======================
================(Epoch: 2 Generation: 200)=======================
{'max': 28, 'min': 10, 'avg': 18.4}
Best:  0
================(Epoch: 2 Generation: 200)=======================
================(Epoch: 3 Generation: 300)=======================
{'max': 28, 'min': 3, 'avg': 11.9}
Best:  0
================(Epoch: 3 Generation: 300)=======================
================(Epoch: 4 Generation: 400)=======================
{'max': 26, 'min': 6, 'avg': 16.2}
Best:  0
================(Epoch: 4 Generation: 400)=======================
================(Epoch: 5 Generation: 500)========

In [86]:
!make maximization

python -m src.examples.sum_maximization
nbits: 5
Generating Population With: 
	- Gene Size: 10
	- Population Size: 20
	- Population Type: <class 'bool'>
	- Generations: 1000
	- Generations for each ephoch: 100
	- Selection Count: 10
            
================(Epoch: 1 Generation: 100)=======================
{'max': 61, 'min': 14, 'avg': 38.6}
Best:  62
================(Epoch: 1 Generation: 100)=======================
================(Epoch: 2 Generation: 200)=======================
{'max': 55, 'min': 16, 'avg': 34.4}
Best:  62
================(Epoch: 2 Generation: 200)=======================
================(Epoch: 3 Generation: 300)=======================
{'max': 56, 'min': 4, 'avg': 31.9}
Best:  62
================(Epoch: 3 Generation: 300)=======================
================(Epoch: 4 Generation: 400)=======================
{'max': 53, 'min': 5, 'avg': 29.75}
Best:  62
================(Epoch: 4 Generation: 400)=======================
================(Epoch: 5 Generation: 500)=

In [87]:
!make skills

python -m src.examples.skills_optimization
Generating Population With: 
	- Gene Size: 6
	- Population Size: 10
	- Population Type: <class 'bool'>
	- Generations: 1000
	- Generations for each ephoch: 100
	- Selection Count: 10
            
================(Epoch: 1 Generation: 100)=======================
{'max': 26, 'min': -988, 'avg': -378.3}
Best:  26
================(Epoch: 1 Generation: 100)=======================
================(Epoch: 2 Generation: 200)=======================
{'max': 26, 'min': -2964, 'avg': -574.9}
Best:  26
================(Epoch: 2 Generation: 200)=======================
================(Epoch: 3 Generation: 300)=======================
{'max': 23, 'min': -2976, 'avg': -480.2}
Best:  26
================(Epoch: 3 Generation: 300)=======================
================(Epoch: 4 Generation: 400)=======================
{'max': 23, 'min': -2976, 'avg': -878.6}
Best:  26
================(Epoch: 4 Generation: 400)=======================
================(Epoch: 5 Gene

# **O Problema: Caixeiro Viajante**


Definição: O Caixeiro precisa passar por todas as cidades da rota utilizando o menor trajeto. 

Distâncias entre as cidades:

    1->2 = 100
    1->3 = 100
    1->4 = 400
    2->1 = 110
    2->3 = 250
    2->4 = 500
    3->1 = 100
    3->2 = 200
    3->4 = 500
    4->1 = 400
    4->2 = 500
    4->3 = 500

O carteiro deve começar o seu trajeto a partir de uma das cidades. Caso não definido o algoritmo deverá selecionar a melhor cidade para iniciar  o trajeto.


## Modelagem do Problema

In [109]:
#@title Modelagem do Problema { run: "auto", vertical-output: true, display-mode: "form" }

import sys
import numpy as np
from src import GeneticAlgorithm
from src.utils.binary_ops import bitsNeededToNumber
from src.utils.binary_ops import bitsToBytes

dist1_2 = 100 #@param {type:"slider", min:0, max:500, step:1}
dist1_3 = 100 #@param {type:"slider", min:0, max:500, step:1}
dist1_4 = 400 #@param {type:"slider", min:0, max:500, step:1}
dist2_1 = 110 #@param {type:"slider", min:0, max:500, step:1}
dist2_3 = 250 #@param {type:"slider", min:0, max:500, step:1}
dist2_4 = 500 #@param {type:"slider", min:0, max:500, step:1}
dist3_1 = 103 #@param {type:"slider", min:0, max:500, step:1}
dist3_2 = 206 #@param {type:"slider", min:0, max:500, step:1}
dist3_4 = 500 #@param {type:"slider", min:0, max:500, step:1}
dist4_1 = 390 #@param {type:"slider", min:0, max:500, step:1}
dist4_2 = 500 #@param {type:"slider", min:0, max:500, step:1}
dist4_3 = 500 #@param {type:"slider", min:0, max:500, step:1}

distancias = np.array([
  [0,dist1_2,dist1_3,dist1_4],
  [dist2_1,0,dist2_3,dist2_4],
  [dist3_1,dist3_2,0,dist3_4],
  [dist4_1,dist4_2,dist4_3,0]            
])

print("matriz de distancias:\n",distancias)


matriz de distancias:
 [[  0 100 100 400]
 [110   0 250 500]
 [103 206   0 500]
 [390 500 500   0]]


In [108]:
#@title Editando manualmente { run: "auto", vertical-output: true }

city1 = 1 #@param [1, 2, 3, 4]
city2 = 2 #@param [1, 2, 3, 4]
city3 = 3 #@param [1, 2, 3, 4]
city4 = 4 #@param [1, 2, 3, 4]

def calculaDist(travel):
  travel_tuple = np.concatenate((travel.T,np.roll(travel.T,-1)),axis=1)-1
  travelDists = distancias[travel_tuple[:,0],travel_tuple[:,1]]
  return np.sum(travelDists), travelDists



travel = np.array([[city1,city2,city3,city4]], np.int32)
dist, dists = calculaDist(travel)

if np.unique(travel).size<4:
  print("caminho incompleto")
else:
  print("caminho:",  "->".join(map(str,travel[0].tolist())))
  print("distancias:",  "->".join(map(str,dists.tolist())),"=",dist)


caminho: 1->2->3->4
distancias: 100->250->500->390 = 1240


In [ ]:
#

In [ ]:
n_city = 4


def main():

    gene_size = n_city*bitsNeededToNumber(n_city)
    nbits = int(round(gene_size/n_city))


    def fitness(gene):
        one = bitsToBytes(gene[:, 0:nbits])
        two = bitsToBytes(gene[:, nbits:])
        score = np.sum([one, two], axis=0)

        # print(one,two,score)
        return score

    print('nbits:', nbits)
    expected = bitsToBytes(np.array([[True]*5])) + \
        bitsToBytes(np.array([[True]*5]))
    # print('DesiredValue:', expected)

    ga = GeneticAlgorithm.GA(gene_size, population_size=20,
                             epochs=1000, ephoc_generations=100, maximization=True)

    ga.debug = False
    ga.verbose = True

    best, pop, score = ga.run(fitness, multiple=True)
    # print(score)

    def evaluate(gene):
        print('==========Evaluation=============')
        one_bits = gene[:, 0:nbits]
        # print(one_bits.shape)
        one = bitsToBytes(one_bits)
        two = bitsToBytes(gene[:, nbits:])
        score = np.sum([one, two], axis=0)

        # print(one,two,score)
        print('Achieved: ', score, 'Expected:', expected)
        
        return score
    print('BEST: ', best)
    evaluate(np.array([best]))
    # print(ga.history['statistics'])


main()